---
name: Coverage

on:
  push:

jobs:
  test:
      name: Test Coverage
      runs-on: ubuntu-latest

      steps:
      - name: Checkout develop
        uses: actions/checkout@v2

      #Installs node.js
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm install
     
      - run: npx nx run-many --target=test --all --parallel --coverage
      - run: node ./tools/coverageMerger.js
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/**/lcov.info
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
