---
name: Coverage

on:
  push:

jobs:
  test:
      name: Generate cache
      runs-on: ubuntu-latest

      steps:
      - name: Checkout develop
        uses: actions/checkout@v2
      - uses: codecov/codecov-action@v2
        with:
          files: ./coverage/apps/nxtester/lcov.info
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
